# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.TextField(),
        ),
    ]
