# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20160205_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
