# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20160216_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
