# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20160216_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='etag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
