# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_auto_20160216_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
