# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sps', '0005_agency_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='urls',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
