# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sps', '0006_agency_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='company',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
