# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sps', '0007_auto_20160320_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
