# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-28 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='format',
            field=models.CharField(default='markdown', max_length=200),
        ),
    ]
